# Generated by Django 5.2.4 on 2025-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
